%% rebar3 plugin provider: regenerate apps/shurbej_web/src/shurbej_schema_data.erl
%% from apps/shurbej_web/priv/schema.json.
%%
%% Runs automatically as a pre-compile hook (see `provider_hooks` in the
%% top-level rebar.config) but does an mtime staleness check first — so
%% compiles after `schema.json` hasn't changed are a cheap no-op.
%%
%% Force a regenerate with `rebar3 gen_schema --force`.
-module(shurbej_gen_schema_prv).
-behaviour(provider).

-include_lib("kernel/include/file.hrl").

-export([init/1, do/1, format_error/1]).

-define(PROVIDER, gen_schema).
-define(IN_FILE,  "apps/shurbej_web/priv/schema.json").
-define(OUT_FILE, "apps/shurbej_web/src/shurbej_schema_data.erl").

init(State) ->
    Provider = providers:create([
        {name, ?PROVIDER},
        {module, ?MODULE},
        {bare, true},
        {deps, []},
        {example, "rebar3 gen_schema"},
        {opts, [
            {force, $f, "force", boolean,
             "Regenerate even if the output is newer than the input"}
        ]},
        {short_desc, "Regenerate shurbej_schema_data.erl from priv/schema.json"},
        {desc, "Regenerate apps/shurbej_web/src/shurbej_schema_data.erl from "
               "apps/shurbej_web/priv/schema.json when the source is newer "
               "(or missing from disk). Use --force to bypass the mtime check."}
    ]),
    {ok, rebar_state:add_provider(State, Provider)}.

do(State) ->
    {Opts, _} = rebar_state:command_parsed_args(State),
    Force = proplists:get_value(force, Opts, false),
    Dir = rebar_state:dir(State),
    InFile  = filename:join(Dir, ?IN_FILE),
    OutFile = filename:join(Dir, ?OUT_FILE),
    case needs_regen(InFile, OutFile, Force) of
        false ->
            rebar_api:debug("gen_schema: ~s up-to-date", [?OUT_FILE]),
            {ok, State};
        true ->
            ok = regen(InFile, OutFile),
            rebar_api:info("gen_schema: wrote ~s", [?OUT_FILE]),
            {ok, State};
        {error, Reason} ->
            {error, format_error(Reason)}
    end.

format_error({missing_input, Path}) ->
    io_lib:format("gen_schema: input file not found: ~s", [Path]);
format_error(Reason) ->
    io_lib:format("~p", [Reason]).

%% ===================================================================
%% Internal
%% ===================================================================

needs_regen(_In, _Out, true) ->
    true;
needs_regen(In, Out, false) ->
    case file:read_file_info(In) of
        {error, _} ->
            {error, {missing_input, In}};
        {ok, InInfo} ->
            case file:read_file_info(Out) of
                {ok, OutInfo} ->
                    InInfo#file_info.mtime > OutInfo#file_info.mtime;
                _ ->
                    true
            end
    end.

regen(InFile, OutFile) ->
    {ok, Bin} = file:read_file(InFile),
    Schema = json:decode(Bin),
    ItemTypes = [maps:get(<<"itemType">>, IT)
                 || IT <- maps:get(<<"itemTypes">>, Schema, [])],
    ok = filelib:ensure_dir(OutFile),
    {ok, Fd} = file:open(OutFile, [write, {encoding, utf8}]),
    try
        io:format(Fd, "%% Generated by shurbej_gen_schema plugin — do not edit.~n", []),
        io:format(Fd, "-module(shurbej_schema_data).~n", []),
        io:format(Fd, "-export([schema/0, item_types/0]).~n~n", []),
        io:format(Fd, "schema() ->~n    ~p.~n~n", [Schema]),
        io:format(Fd, "item_types() ->~n    ~p.~n", [ItemTypes])
    after
        file:close(Fd)
    end,
    ok.
